version: '3.8'
services:
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    container_name: firestore-emulator
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8091
    ports:
      - "8091:8091"