spring:
  application.name: spring-aws

  cloud:
    aws:
      endpoint: http://localhost:4566
      region.static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      s3:
        chunked-encoding-enabled: false # Floci does not always handle chunked encoding properly
      sqs:
        queue-not-found-strategy: fail
